### ISSUE TITLE
Add behat tests

### ISSUE THREAD

**Issue by nikpap** [DigiDago/moodle-block_course_modulenavigation#12]

**Comment by clementpr** [comment]
@CrymSonir : 
La semaine prochaine il faut que nous fassions un point rapide (10 minutes) pour décider si on intègre Behat ou pas à court terme (10 jours). 
En fonction, il faudrait également tester le plugin avec Moodle 3.4 (à priori rien de particulier à confirmer) et mettre à jour l'application sur le répertoire officiel Moodle : https://moodle.org/plugins/block_course_modulenavigation

Deadline : Monday 8 Novembre (pour avoir le badge early bird de Moodle)

**Comment by CrymSonir** [comment]
Ça pourra se faire facilement maintenant qu'on c'est fait la main sur celui de block_mylastmessage
