### ISSUE TITLE
Bug: Problem with TOC when bootstrap elements plugin used in course

### ISSUE THREAD

**Issue by mojaedukacja** [DigiDago/moodle-block_course_modulenavigation#58]
Problem with TOC when bootstrap elements plugin used in course

On the table of contents (navigation) the name of the module / activity with a suffix is displayed (eg. bootstrap lements1) instead of the name (title) of the given for activity / resource.

**Comment by clementpr** [comment]
Hi,

Thank you for your feedback. Do you have a screenshot of this bug ?

**Comment by mojaedukacja** [comment]
![2019-07-05_10h12_26](https://user-images.githubusercontent.com/37048265/60708326-19a34600-9f0e-11e9-9a04-ee513a347b31.png)

**Comment by kecherou** [comment]
Hi @mojaedukacja,

In fact the TOC displays the name of the modules.
But the bootstrap element module has as name the name of the element and it real name is put in the field "title". The name of an activity / ressource has to be in the field "name" but the bootstrap element plugin use this field differently.

![Capture d’écran 2019-07-05 à 11 20 28](https://user-images.githubusercontent.com/18518025/60712896-478d8800-9f18-11e9-928f-0e9ea60c6ed5.png)

**Comment by mojaedukacja** [comment]
so maybe...
exception if module == bootstrapelements take from title? :)

**Comment by mojaedukacja** [comment]
Any chance to introduce the above workaround or other solution to the problem?

**Comment by mojaedukacja** [comment]
September... no response....

**Comment by clementpr** [comment]
Hi,
We gave you a detailed answer in June. The problem comes from bootstrap elements plugin. 
We prefer to keep this plugin fully working with moodle core and we unfortunately have no time to take care of the exceptions caused by third-party plugin.
Regards

**Comment by mojaedukacja** [comment]
Workaround: run from time to time a sql query 

UPDATE `PREFIX_bootstrapelements` SET `name`=`title`

close and waiting for fix from Bootstrap Elements team
