### ISSUE TITLE
Please remove French language strings for this plugin

### ISSUE THREAD

**Issue by germanvaleroelizondo** [DigiDago/moodle-block_course_modulenavigation#62]
The French language strings have been sent to AMOS and accepted.

See https://lang.moodle.org/local/amos/contrib.php?id=31448

Please remove the French language strings here in GitHub.

Please use AMOS for further translations of this and other Moodle plugins.

**Comment by CrymSonir** [comment]
Hello,

I deleted the FR language file and made some corrections to the FR string on Amos.

Best regards,
