### ISSUE TITLE
Display restricted activities in menu

### ISSUE THREAD

**Issue by ghost** [DigiDago/moodle-block_course_modulenavigation#63]
Feature request -

This is a great plugin, but would it be possible to have an option to have activities that are access restricted to appear to students in the course module navigation menu and have them grayed out and unclickable (without URL) (like a label). When access restriction criteria is met and activity opens to student, then the activity would become clickable and be displayed in standard UI style.

For example:
![course_module_navigation](https://user-images.githubusercontent.com/57189646/75275281-4d4f1b00-57d2-11ea-9a67-0a481497d1e2.png)

**Comment by CrymSonir** [comment]
Hello,
Sorry for the delay in our response.
Indeed it seems to me to be an interesting feature.
However, we do not have time to deal with it at the moment.
I will leave your issue open and we will try to integrate this feature when we have enough time to devote to it.
Best regards,

**Comment by CrymSonir** [comment]
This problem will be addressed in the next plugin update.
