### ISSUE TITLE
Titles not shown without visible activity

### ISSUE THREAD

**Issue by onword** [DigiDago/moodle-block_course_modulenavigation#71]
**Describe the bug**
Topics/sections are not shown in course module navigation unless there is an activity in a topic, causes an issue navigating with  [Onetopic course format](https://moodle.org/plugins/format_onetopic)

**To Reproduce**
- Install Onetopic
- Set a courseto course format: Onetopic
- Add block course module navigation
- Notice that topics/sections without activities are not shown in the navigation titles.

**Expected behavior**
Expected topics/sections to be shown as titles even if an actitivy was not present

**Screenshots**
![Screenshot 2021-06-08 9 17 56 PM](https://user-images.githubusercontent.com/78563574/121280292-0ccec000-c8a4-11eb-863e-e54c4802d22a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Tried on Windows 10 and ChromeOS
 - Browser [e.g. chrome, safari] Chrome, new Microsoft Edge 
 - Version [e.g. 22] Chrome 91.0.4472.81, not sure about Edge, but should be the latest stable as auto updates are turned on

**Smartphone (please complete the following information):**

**Additional context**
If possible the ability to show titles in the navigation area even if activities do not exist is important because - especially with Onetopic course format - A topic can be created without activities to just show text using the section "summary" area, letting the teacher display information without requiring the student to click an activity. This would work very well with course module navigation's option "clicking on title goes to that page" in many course formats.

I tried to create a dummy activity and hide it to see if the topic itself would show in course module navigation, but it did not work.

**Comment by onword** [comment]
Thank you! Yes let me know!

**Comment by CrymSonir** [comment]
Hello,

After some discussion, we could consider adding an option to allow the expected behavior.

But this is not very simple and currently we do not really have the time to take care of it.

Best regards,
Sylvain - Pimenko Team.

**Comment by onword** [comment]
Thanks Sylvain, understood. Is there anything I can do to help besides wait?

**Comment by CrymSonir** [comment]
Hello,

Once again, I apologize for the delayed response. We are no longer actively maintaining this plugin, but simply conducting routine checks for compatibility with the latest Moodle versions.
