### ISSUE TITLE
v4.6.1 missing on GitHub

### ISSUE THREAD

**Issue by michael-milette** [DigiDago/moodle-block_course_modulenavigation#82]
I noticed that the version here on GitHub is only at v4.6 however the version on Moodle.org (https://moodle.org/plugins/block_course_modulenavigation) has version 4.6.1 available for download.

Could you please update the code on GitHub? It would be very much appreciated. :-)

Best regards,

Michael Milette

**Comment by CrymSonir** [comment]
Hello Michael,

Use tag https://github.com/DigiDago/moodle-block_course_modulenavigation/releases/tag/v4.6.1

Or u can use one of the principale branch MOODLE_401_STABLE / MOODLE_400_STABLE

I think there was a mistake in the patch of the 'release' line in the version.php file but these are the most up-to-date code versions.

Best regards,
